#!/bin/bash
# Bash script written from the tutorial of brain0 posted on 29/05/2010

#image location
IMG_LOC="/home/ignas/downloads/archlinux-2010.05-netinstall-dual.iso"

fdisk -u -l -c /dev/sdb & read -n1
cfdisk /dev/sdb
fdisk -u -l -c /dev/sdb & read -n1
mkfs.vfat -n gnsank /dev/sdb1
mkfs.ext2 /dev/sdb2

tune2fs -i0 -c0 -m0 /dev/sdb2
e2label /dev/sdb2 ARCH_201005

#mounting stuff
if [ ! -d /mnt/archiso ]; then mkdir /mnt/archiso; fi
if [ ! -d /mnt/usbboot ]; then mkdir /mnt/usbboot; fi
mount -o loop,ro ${IMG_LOC} /mnt/archiso || return 1
mount /dev/sdb2 /mnt/usbboot || return 1
cp -a /mnt/archiso/* /mnt/usbboot/ || return 1
umount /mnt/archiso || return 1

#bootloader section
BOOTDIR="/mnt/usboot/boot"
mv ${BOOTDIR}/isolinux ${BOOTDIR}/extlinux
rm ${BOOTDIR}/extlinux/isolinux.bin
mv ${BOOTDIR}/extlinux/isolinux.cfg ${BOOTDIR}/extlinux/extlinux.conf
extlinux --install /mnt/usbboot/boot/extlinux/
umount /mnt/usbboot
cat /usr/lib/syslinux/mbr.bin > /dev/sdb

fdisk -u -l -c /dev/sdb & read -n1
